stages:
    - prepare
    - build
    - package
    - deploy
    - finalize

.production:
    only:
        - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i

include:
    - local: .gitlab/build/linux.gitlab-ci.yml
    - local: .gitlab/build/windows.gitlab-ci.yml
    - local: .gitlab/build/macos.gitlab-ci.yml
    - local: .gitlab/deploy.gitlab-ci.yml
    - local: .gitlab/finalize.gitlab-ci.yml
